# Generated by Django 5.1.3 on 2025-06-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=500, verbose_name='Наименование организации')),
                ('deep', models.IntegerField(verbose_name='Глубина окна')),
                ('average', models.IntegerField(verbose_name='Среднее время ожидания по талону')),
                ('active', models.BooleanField(verbose_name='Активность окна')),
            ],
            options={
                'verbose_name': 'Информация',
            },
        ),
    ]
