# Generated by Django 5.2.3 on 2025-06-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AlterField(
            model_name='information',
            name='active',
            field=models.IntegerField(verbose_name='Активность окна'),
        ),
    ]
