# Generated by Django 5.2 on 2025-06-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_information_options_alter_information_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('someint', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тест',
                'db_table': 'test',
            },
        ),
        migrations.AlterField(
            model_name='information',
            name='active',
            field=models.IntegerField(verbose_name='Активные окна'),
        ),
    ]
