# Generated by Django 5.2 on 2025-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_test_alter_information_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(verbose_name='ID отдела')),
                ('name', models.CharField(verbose_name='Имя отдела')),
                ('description', models.CharField(verbose_name='Расшифровка')),
                ('unit_id', models.IntegerField(verbose_name='ID офиса')),
            ],
            options={
                'verbose_name': 'Отделы офиса',
                'verbose_name_plural': 'Отделы офиса',
            },
        ),
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talon_id', models.IntegerField()),
                ('fio', models.CharField(verbose_name='ФИО заявителя')),
                ('ser_day', models.TimeField(verbose_name='Дата резервирования')),
                ('full_number', models.CharField(verbose_name='Полный номер талона')),
            ],
            options={
                'verbose_name': 'Талон',
                'verbose_name_plural': 'Талоны',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(verbose_name='ID офиса')),
                ('name', models.CharField(verbose_name='Название офиса')),
                ('short_name', models.CharField(verbose_name='Компактное название офиса')),
                ('work_time_id', models.IntegerField(verbose_name='рабочее время офиса')),
                ('pre_record_time_id', models.IntegerField(verbose_name='расписание пред записи')),
            ],
            options={
                'verbose_name': 'Офисы',
                'verbose_name_plural': 'Офисы',
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_id', models.IntegerField()),
                ('active', models.IntegerField(verbose_name='Активность окна')),
                ('department_id', models.IntegerField(verbose_name='Номер департамента')),
                ('online', models.IntegerField(verbose_name='Онлайн ли окно')),
            ],
            options={
                'verbose_name': 'Окно',
                'verbose_name_plural': 'Окна',
            },
        ),
        migrations.CreateModel(
            name='Work_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField()),
                ('description', models.CharField(verbose_name='Название и тип расписания')),
                ('mon_prerecord_factor', models.IntegerField(verbose_name='Процент пред записи на понедельник')),
                ('tue_prerecord_factor', models.IntegerField(verbose_name='Процент пред записи на вторник')),
                ('wed_prerecord_factor', models.IntegerField(verbose_name='Процент пред записи на среду')),
                ('thu_prerecord_factor', models.IntegerField(verbose_name='Процент пред записи на четверг')),
                ('fri_prerecord_factor', models.IntegerField(verbose_name='Процент записи на пятницу')),
                ('sat_prerecord_factor', models.IntegerField(verbose_name='Процент записи на субботу')),
            ],
            options={
                'verbose_name': 'Рабочее время',
                'verbose_name_plural': 'Рабочее время',
            },
        ),
        migrations.CreateModel(
            name='Work_time_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time_range_id', models.IntegerField()),
                ('time_from', models.CharField(verbose_name='Время начала интервала')),
                ('time_to', models.CharField(verbose_name='Время конца интервала')),
                ('mon', models.IntegerField(verbose_name='Интервал работает в ПН')),
                ('tue', models.IntegerField(verbose_name='Интервал работает в ВТ')),
                ('web', models.IntegerField(verbose_name='Интервал работает в СР')),
                ('thu', models.IntegerField(verbose_name='Интервал работает в ЧТ')),
                ('fri', models.IntegerField(verbose_name='Интервал работает в ПТ')),
                ('sat', models.IntegerField(verbose_name='Интервал работает в СБ')),
                ('sun', models.IntegerField(verbose_name='Интервал работает в ВС')),
                ('unit_id', models.IntegerField(verbose_name='ID отдела')),
            ],
            options={
                'verbose_name': 'Интервалы',
                'verbose_name_plural': 'Интервалы',
            },
        ),
    ]
