# Generated by Django 5.2 on 2025-07-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_department_talon_unit_window_work_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table=None,
        ),
    ]
